---
title: 'ALY6010: Module 1 R Practice'
subtitle: 'Bla bla'
author: "Shamim Sherafati"
date: "2022-11-6"
output:
  html_document:
    df_print: paged
  pdf_document: default
---
### Importing packages: *FSA, FSAdata, magrittr, dplyr, tidyr, plyr and tidyverse*
```{r}
# install.packages("plyr")   # Import Libraries
# install.packages("dplyr")
# install.packages("tidyr")
# install.packages("tidyverse")
#install.packages("psych")
#install.packages("ggpubr")
# install.packages("ggplot2")
# install.packages("scales")
#install.packages("plotly")
#install.packages("ggmosaic")

library(plyr) 
library(dplyr)
library(tidyr)
library(dplyr)
library(ggplot2)
library(ggpubr)
library(tidyverse)
library(psych)
library(moments)
library(scales)
```

### Import the file *AB_NYC_2019.csv* and show basic info
```{r}
bank_unclean = read.csv("~/Downloads/Archive (1)/bank.csv")
```

```{r}
# Sorted dataframe with descending age
bank_sort= bank_unclean[order(-bank_unclean$age),]
head(bank_sort)

# Drop column "default"
bank_drop = select(bank_sort, -5)
head(bank_drop)

# Rename column 
names(bank_drop)[names(bank_drop) == 'contact'] <- 'Contact_Info'
head(bank_drop)

# Remove the top 55 % and bottom 45%
bank = bank_drop[6139:5022,] # Remove the top 55 % and bottom 45%

# Replace column string to Captial letters using GSUB
bank$marital<-gsub("single","SINGLE",as.character(bank$marital))
bank$marital<-gsub("married","MARRIED",as.character(bank$marital))
bank$marital<-gsub("divorced","DIVORCED",as.character(bank$marital))
head(bank)
```
```{r}
#Mean, Min, Max, STD of each age balance
bank %>%
group_by(age)%>%
summarise_at(vars(balance),list(Mean=mean, Min=min, Max=max,STD=sd))

#Mean, Min, Max, STD of each campaign duration
bank %>%
group_by(campaign)%>%
summarise_at(vars(duration),list(Mean=mean, Min=min, Max=max,STD=sd))

```

```{r}
ggplot(data = bank) + geom_bar(mapping = aes(x=marital, fill=education), position="dodge") + labs(title="The Impact Of Marital On Education", x ="Marital Stauts", y = "Count")
```

```{r}
ggplot(data = bank) + geom_bar(mapping = aes(x=age, fill=housing), position="dodge") + labs(title="Housing At Different Ages", x ="Age", y = "Housing")
```

```{r}
ggplot(data = bank_unclean) + geom_bar(mapping = aes(x=age, fill=housing), position="dodge") + labs(title="Housing At Different Ages-unclean data", x ="Age", y = "Housing")
```

```{r}
hist(bank$age, main= "age-contact info" , xlab= "Age (yrs)" , ylab= "contact-info", col="cadetblue", col.main="red", las=1)
```
```{r}
ggplot(data = bank) + geom_bar(mapping = aes(x=age, fill= Contact_Info), position="dodge") + labs(title="Different contact info based on different Ages", x ="Age", y = "contact-info")
```
```{r}
table(bank$age)
```
```{r}
#Top 6 jobs based on different ages
bankrank<- bank %>%
  
select(education,age, job)

Mostjob <- aggregate(age ~ job, bankrank, mean)
slice( Mostjob[order(-Mostjob$age),],
1:10)

```
```{r}
#create box plot for top 6 jobs based on the previous code

boxplot( bankrank$age ~ bankrank$job, main="Top 6 jobs based on different ages", xlab = "job", ylab = "age ", col = "purple")
```

```{r}
box1 <- boxplot( bank$age ~ bank$housing, main="box plot of Housing based on different ages", xlab = "housing", ylab = "age ", col = "light green")
```
```{r}
box2 <- boxplot( bank$age ~ bank$loan, main="box plot of getting loan based on different ages", xlab = "loan", ylab = "age ", col = "light pink")
```

```{r}
ggplot(bank, aes(x = "bank$housing + bank$age" , y = "bank$loan + bank$age" , color = "")) +  # ggplot function
  geom_boxplot()

```
```{r}
ggplot(bank, aes(x = education, y = loan, color = "green")) +  # ggplot function
  geom_boxplot()
```

```{r}
ggplot(bank, aes(x = age, y = Contact_Info, color = "green")) +  # ggplot function
  geom_boxplot()
```

```{r}
library(plotly)
plot_ly( data = bank,
  x = ~job,
  type = "histogram")
```

```{r}
bank%>%
  group_by(loan) %>%
  do(p=plot_ly(., x = ~log(day),name =~age, type = "histogram")) %>%
  subplot(nrows = 1, shareX = FALSE, shareY = TRUE)
```

```{r}
bank%>%
  group_by(age) %>%
  do(p=plot_ly(., x = ~log(campaign),name =~Contact_Info, type = "histogram")) %>%
  subplot(nrows = 1, shareX = FALSE, shareY = TRUE)
```

```{r}
bankdens <- density(log(bank$age))
 
plot_ly( data = bank,
  x = ~log(age),
  type = "histogram",
  name = "age") %>% 
  add_lines(x = bankdens$x, y = bankdens$y, yaxis = "y2", name = "education") %>% 
  layout(yaxis2 = list(overlaying = "y", #Adds the dual y-axis
                       side = "right", #Adds the density axis on the right side
                       rangemode = "tozero")) #Forces both y-axes to start at 0
```

```{r}
plot_ly( data = bank,
  x = ~age,
  y = ~log(campaign),
  type = "violin",
  color = ~"red",
  side = "positive",
  meanline = list(visible = T))

```

```{r}
#install.packages('gmodels')
library('gmodels')

banl_ct <- CrossTable(bank$job, bank$age,
                 dnn = c("Job", "Age"))
```

```{r}
banl_ct2 <- CrossTable(bank$job, bank$education,
                 dnn = c("Job", "Education"))
```

```{r}
banl_ct3 <- CrossTable(bank$age, bank$housing,
                 dnn = c("Age", "Housing"))
```

```{r}
#1st- Frequency Table

bank_table = table(bank$education, bank$job) # A will be rows, B will be columns 
bank_table # print table

margin.table(bank_table, 1) # neighbourhood_group frequencies (summed over room_type) 
margin.table(bank_table, 2) # room_type frequencies (summed over neighbourhood_group)

prop.table(bank_table) # cell percentages
prop.table(bank_table, 1) # row percentages 
prop.table(bank_table, 2) # column percentages

```

```{r}
#2nd-Frequency Table 
bank_Ftable1 = table(bank$age, bank$job) 
ftable(bank_Ftable1)
```

```{r}
bank_Ftable2 = table(bank$deposit, bank$age) 
ftable(bank_Ftable2)
```

```{r}
bank_Ftable3 = table(bank$Contact_Info, bank$marital) 
ftable(bank_Ftable3)
```







